name: Test and Build

on:
    push:
        branches: 
            - main

            
jobs:
    Test-Build-e2e-publish:
        runs-on: self-hosted

        steps: 
            - name: Checkout Code
              uses: actions/checkout@v4
            
            # - name: Ensure aws & docker present
            #   run: |
            #     command -v aws || sudo apt-get update && sudo apt-get install -y awscli
            #     docker --version

            - name: Ensure pytest
              run: |
                        set -euxo pipefail
                        python -m pip install --upgrade pip
                        # If you have project deps, install them first
                        if [[ -f requirements.txt ]]; then
                        pip install -r requirements.txt
                        fi
                        if [[ -f pyproject.toml || -f setup.py ]]; then
                        pip install -e .
                        fi
                        # Make sure pytest is present (and coverage if you use it)
                        pip install --upgrade pytest pytest-cov
                        # Sanity check
                        python -m pytest --version 


            - name: unit test app
              run: pytest -q

            - name: Login to ECR (uses instance profile automatically)
              env:
                AWS_REGION: ap-south-1
              run: |
                REGISTRY=$(aws sts get-caller-identity --query Account --output text).dkr.ecr.$AWS_REGION.amazonaws.com
                aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REGISTRY
            


        