name: Test and Build

on:
    push:
        branches: 
            - main

            
jobs:
    Test-Build-e2e-publish:
        runs-on: self-hosted

        steps: 
            - name: Checkout Code
              uses: actions/checkout@v4
            
            # - name: Ensure aws & docker present
            #   run: |
            #     command -v aws || sudo apt-get update && sudo apt-get install -y awscli
            #     docker --version
            - uses: actions/setup-python@v5
              with:
                python-version: "3.12"
                cache: "pip"

            - name: Ensure pytest
              run: |
                        python -m pip install --upgrade pip
                        if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi
                        pip install -U pytest pytest-cov
                        python -m pytest --version


            - name: unit test app
              run: pytest -q

            - name: Login to ECR (uses instance profile automatically)
              env:
                AWS_REGION: ap-south-1
              run: |
                REGISTRY=$(aws sts get-caller-identity --query Account --output text).dkr.ecr.$AWS_REGION.amazonaws.com
                aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REGISTRY
            


        